

name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print env and expression
        run: |
          echo "env: $GITHUB_TOKEN"
          echo "expression: ${{ secrets.GITHUB_TOKEN }}"
        env:
          GITHUB_TOKEN: ${{ secrets.MYSECRETS }}
      - name: Print My Secrets
        run : |
          echo "My Secrets: $MYSECRETS"
          echo "expression: ${{ secrets.MYSECRETS }}"
        env:
          MYSECRETS: ${{ secrets.MYSECRETS }}


